### ISSUE TITLE
Issue with changing from Solo to Pro after install

### ISSUE THREAD

**Issue by jamie-jenks** [craftcms/stripe#4] opened 2024-05-02 16:29 UTC
### Description

Craft displays an error when attempting to go to the URL: "/admin/myaccount" after swapping from Solo to Pro.

Error: 

Unknown Method – [yii\base\UnknownMethodException](https://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html)

Calling unknown method: craft\elements\User::getStripeCustomers()

### Steps to reproduce

1. Install Craft as a Solo license 
2. Install Stripe 
3. Configure Stripe 
4. Realise you're running Solo instead of Pro
5. Swap to Pro
6. Visit: "/admin/myaccount" & the error will show

### Additional info

- Craft version: 5.1.0
- PHP version: 8.2
- Database driver & version: mariadb:10.5
- Plugins & versions: Stripe - 1.0.0

**Comment by i-just** [comment] 2024-05-03 07:10
Hi, thanks for reaching out! I can’t replicate this behaviour. Could you please clear your template (or all) caches and see if the issue persists?

**Comment by jamie-jenks** [comment] 2024-05-03 10:38
@i-just hey,

I tried the above suggestions and still get the error. Do you have an email address I can send my composer and DB to? That might help reproduce.

**Comment by i-just** [comment] 2024-05-03 11:18
Hi @jamie-jenks, can you please send it to support@craftcms.com? Thanks!

**Comment by i-just** [comment] 2024-05-07 08:26
@jamie-jenks, thanks again for sending over the files. I tracked down the cause of this issue and raised a PR for it. You might also run into a MariaDB-specific bug, which is also actioned on the same PR. Thanks again for reporting!

**Comment by brandonkelly** [comment] 2024-05-07 12:41
Stripe 1.0.1 is out with the fix for this. Thanks again!

**Closed as completed by brandonkelly** 2024-05-07 12:41 UTC
Labels: bug
